#!/bin/sh

ENABLED=yes
PROCS=AdGuardHome
ARGS="-l /opt/AdGuardHome/AGH.log"
GOMAXPROCS="$(grep -c "processor" /proc/cpuinfo)"
GOMAXPROCS="$((GOMAXPROCS == 4 ? 2 : (GOMAXPROCS == 2 ? 1 : 1)))"
GOMEMLIMIT="$(free | awk -v VAR=$GOMAXPROCS '/Mem/{print int(($4*0.9537/1024)/VAR)}')MiB"
PREARGS="env SSL_CERT_DIR=/opt/etc/ssl/ GOMAXPROCS=${GOMAXPROCS} GOMEMLIMIT=${GOMEMLIMIT} GOGC=40 QUIC_GO_DISABLE_ECN=true"
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/AdGuardHome
. /opt/etc/init.d/rc.func
